### ISSUE TITLE
[Mustashe Package] Stash function does not recognize user-defined function parameter 'vec'

### ISSUE THREAD

**Issue by ghost** [jhrcook/mustashe#12]
Hey its @MichaelSodeke again. I opened a [previous issue ](https://github.com/jhrcook/mustashe/issues/9)(now closed). I have a new issue LOL 😀 .

## Attempt
I am trying to create a data frame containing all region names and their coordinates.
I attempted to automate this task with a `foreach`loop from the `doParallel` package 
and created a user-defined function called `getBounds` parameterized by `vec`, which
takes in a vector of country names from the variable `cntry`. However this process is too
slow. So I decided to use the `stash` function from the `mustashe` package, but for
some reason the `vec` parameter is not reconized within `stash` for each variable:
`lon1`, `lat1`, `lon2`, `lat2`.

Why is `stash` function not recognizing `vec` parameter?

----

## Code
```
# load packages
suppressMessages( require(dplyr) )
suppressMessages( require(doParallel) )
suppressMessages( require(mustashe) )
suppressMessages( require(tictoc) )
suppressMessages( require(maps) )
suppressMessages( require(mapdata) )

# create user-defined function to get bounds for each country
getBounds <- function(vec=NULL)
{
	lon1 <- NULL
	lat1 <- NULL
	lon2 <- NULL
	lat2 <- NULL

	no_cores <- detectCores() - 1
	cl <- makePSOCKcluster(no_cores)
	registerDoParallel(cl,cores=no_cores)

	tic()
	stash("lon1", {
		Sys.sleep(5)
		lon1 <- foreach (i=1:length(vec),.combine='c') %dopar% { maps::map("world",fill=F,region=vec[i],plot=F)$range[1] }
	})
	toc()

	tic()
	stash("lat1", {
		Sys.sleep(5)
		lat1 <- foreach (i=1:length(vec),.combine='c') %dopar% { maps::map("world",fill=F,region=vec[i],plot=F)$range[3] }
	})
	toc()

	tic()
	stash("lon2", {
		Sys.sleep(5)
		lon2 <- foreach (i=1:length(vec),.combine='c') %dopar% { maps::map("world",fill=F,region=vec[i],plot=F)$range[2] }
	})
	toc()

	tic()
	stash("lat2", {
		Sys.sleep(5)
		lat2 <- foreach (i=1:length(vec),.combine='c') %dopar% { maps::map("world",fill=F,region=vec[i],plot=F)$range[4] }
	})
	toc()
	
	stopCluster(cl)

	cbind(lon1,lat1,lon2,lat2)
}
```
----

## Results
```
# get country names
cntry <- map("world",fill=F,plot=F)$names

# implement user-defined function
tic()
location <- getBounds(vec=cntry)
toc()


Stashing object.
Error in eval(a, envir = extra, enclos = obj$evalenv) :
  object 'vec' not found
> toc()
5.38 sec elapsed
```
If I can get the above to work, then I can use the `locations` variable to create the
desired data frame.
```
df <- data.frame(cntry,location)
head(df)
```
----

Logically, `vec` should be recognized, but for unknown reasons this is not the case. 
How can I fix this issue?

**Comment by jhrcook** [comment]
The `stash()` function does not inspect the code within the code block it is passed so it doesn't know if a value within changes. It would only realize something has changed if the code itself changes. To have `stash()` re-run code if another value has changed, you can pass that value as a dependency using the `depends_on=` parameter. For example, you could try something like this:

```r
stash("lat2", depends_on = c("vec"), {
  Sys.sleep(5)
  lat2 <- foreach (i=1:length(vec),.combine='c') %dopar% { maps::map("world",fill=F,region=vec[i],plot=F)$range[4] }
})
```

In the above code, if the variable names `vec` changes value, `stash()` will re-run the code block instead of loading a previously stashed value. See this part of the [README](https://jhrcook.github.io/mustashe/#dependencies) for another example or the [Getting Started](https://jhrcook.github.io/mustashe/articles/getting-started.html#dependencies) vignette for a bit more info.

Another thing to consider is to use the ['memoise'](http://memoise.r-lib.org) package. You could refactor `getBounds()` and pull out the operations that calculate `lon1`, `lat1`, `lon2`, and `lat2` into separate functions then memos each of these.

Let me know if this helps or if I'm not understanding the problem correctly.

**Comment by ghost** [comment]
So I applied your first solution to `getBounds`
```
stash("lon1",depends_on = c("vec"), {
	Sys.sleep(5)
	lon1 <- foreach (i=1:length(vec),.combine='c') %dopar% { maps::map("world",fill=F,region=vec[i],plot=F)$range[1] }
})
```

However, I received the following error:
```
> tic()
> location <- getBounds(vec=cntry)
Error in make_hash(depends_on, .TargetEnv) :
  Some dependencies are missing from the environment.
> toc()
0.12 sec elapsed
```

**Comment by jhrcook** [comment]
This is happening because it is looking for `vec` in the global environment. I'm not sure there is currently a solution to your problem in 'mustashe', but I can think about opening up the `.TargetEnv` parameter in the API. 

---

Actually, after further thought, I think we'll run into a different problem even if we get around the latest error message: 'mustashe' stores variables by their name, not their hash (i.e. not based off of their value). Therefore, if you stash `a` based on one computation, then stash `a` based on another computation, if you re-run the first computation, the original value for `a` will not be available any longer and the code will be re-run. That's why 'mustashe' is a *caching* system, not a *memoization* system (I interpret these as separate objectives).

With that, I will continue to think about adjustments to the package to make it more general, but for now, I would suggest trying to use the ['memoise'](http://memoise.r-lib.org/) package; I think it is more geared towards your goal.

**Comment by ghost** [comment]
Thanks for the info. For now I will just use my original attempt. The algorithm is slow, but gets the job done.
```
# create user-defined function to get bounds for each country
getBounds <- function(vec=NULL)
{
	lon1 <- rep(0,length(vec))
	lat1 <- rep(0,length(vec))
	lon2 <- rep(0,length(vec))
	lat2 <- rep(0,length(vec))
	for (i in 1:length(vec))
	{
		lon1[i] <- map("world",fill=F,region=vec[i],plot=F)$range[1]
		lat1[i] <- map("world",fill=F,region=vec[i],plot=F)$range[3]
		lon2[i] <- map("world",fill=F,region=vec[i],plot=F)$range[2]
		lat2[i] <- map("world",fill=F,region=vec[i],plot=F)$range[4]
	}
	cbind(lon1,lat1,lon2,lat2)
}
```
Here a the results:
```
tic()
location <- getBounds(vec=cntry)
toc()

172 sec elapsed
```
```
df <- data.frame(cntry,location)
head(df)

                   cntry        lon1      lat1        lon2       lat2
1            Afghanistan   60.485744  29.39194   74.891312  38.456398
2                Albania   19.280664  39.65352   21.031054  42.647949
3                Algeria   -8.683350  18.98662   11.967871  37.092384
4 American Samoa:Tutuila -170.820511 -14.35977 -170.568115 -14.257421
5                Andorra    1.414844  42.43447    1.740234  42.642727
6                 Angola   11.743067 -18.01973   24.046680  -4.428906
```

**Comment by jhrcook** [comment]
Sorry I couldn't be much help on this. My intended use-case for 'mustashe,' applied to the code above, would be something like:

```r
stash("location", depends_on="cntry", {
  location <- getBounds(vec=cntry)
})
```

where `location` is unlikely to change very often and takes a longtime to compute. Thus, the next time you are working with the script, `location` does not need to be re-computed, but loaded from the "stash."

Let me know if there is anything else I can help with, else I'll close the issue for now.

**Comment by ghost** [comment]
Hey! Your new solution worked. I made things complicated for no reason. I should've just created my `getBounds` algorithm, then encapsulate the `locations` variable within the `stash` function. Here is the full **Code** and **Result**.
Take care and happy late New Year!

## Code for [index.rmd]
```
---
title: "COVID-19 Tracker"
date: "`r Sys.Date()`"
fontsize: 9pt
fontfamily: Segoe UI
output: flexdashboard::flex_dashboard
runtime: shiny
---
```
```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared
# by all users of the dashboard
suppressMessages( require(dplyr) )
suppressMessages( require(flexdashboard) )
suppressMessages( require(mustashe) )
suppressMessages( require(doParallel) )
suppressMessages( require(tictoc) )
suppressMessages( require(leaflet) )
suppressMessages( require(maps) )
suppressMessages( require(mapdata) )
suppressMessages( require(shiny) )
suppressMessages( require(htmltools) )
suppressMessages( require(htmlwidgets) )
```
```{r,results=FALSE}
cntry <- map("world2Hires",fill=F,plot=F)$names
cntry <- cntry[order(cntry)]
getBounds <- function(vec=NULL)
{
	lng1 <- rep(0,length(vec))
	lat1 <- rep(0,length(vec))
	lng2 <- rep(0,length(vec))
	lat2 <- rep(0,length(vec))
	for (i in 1:length(vec))
	{
		lat1[i] <- map("world2Hires",fill=F,region=vec[i],plot=F)$range[3] %>% round(5)
		lng2[i] <- map("world2Hires",fill=F,region=vec[i],plot=F)$range[2] %>% round(5)
		lat2[i] <- map("world2Hires",fill=F,region=vec[i],plot=F)$range[4] %>% round(5)
		lng2[i] <- map("world2Hires",fill=F,region=vec[i],plot=F)$range[1] %>% round(5)
	}
	cbind(lng1,lat1,lng2,lat2)
}

tic()
stash("location", depends_on="cntry", {
  location <- getBounds(vec=cntry)
})
toc()

df <- data.frame(cntry,location)
```
```
Column {.sidebar}
--------------------------------------------------
Put some text here.
```
```{r}
# https://community.rstudio.com/t/rstudio-connect-interactive-markdown-with-shiny-error-path-for-html-dependency-not-provided/7263/11
selectInput(
	"loc",
	label="Locations:",
	choices = df[1:2284,1],
	selected = df[549,1]
	)
```
```
Column
--------------------------------------------------

### COVID-19 Epicenters
```
```{r}
	# base layer
renderLeaflet({
	leaflet() %>% addTiles() %>%
	# add tile theme layer
	addProviderTiles(providers$CartoDB.Positron) %>%
	# add bounds
	fitBounds(
		lng1=map("world2Hires",fill=F,region=input$loc,plot=F)$range[1],
		lat1=map("world2Hires",fill=F,region=input$loc,plot=F)$range[3],
		lng2=map("world2Hires",fill=F,region=input$loc,plot=F)$range[2],
		lat2=map("world2Hires",fill=F,region=input$loc,plot=F)$range[4]) %>% 
	# add markers
	# add mini map [to aid navigation]
	addMiniMap(
	    tiles=providers$Esri.WorldStreetMap,
	    toggleDisplay=TRUE) %>%
	# add easy button [for zooming]
	addEasyButton(easyButton(
	    icon="fa-globe", title="Zoom to Level 3",
	    onClick=JS("function(btn, map){ map.setZoom(3); }") ))
})

```
## Result
```
rmarkdown::run()
```
![img](https://user-images.githubusercontent.com/52264341/104105848-00e3c100-5266-11eb-8d05-aa4d6576bf5e.PNG)

**Comment by jhrcook** [comment]
I'm glad it worked and I'm happy I could help. I hope you have a happy New yYear, too!
