### ISSUE TITLE
An option for stash to return invisibly the object itself

### ISSUE THREAD

**Issue by traversc** [jhrcook/mustashe#16]
Since `stash` is currently returning NULL, a simple use for the return value would be the result of the expression. This would allow people to use `stash` in a more functional-programming way. 

Here's a simplified example of some work I was trying to cache earlier. 

```
library(mustashe)
library(ggplot2)
library(patchwork)

long_running_function <- function(i) {
  data.frame(x = runif(i^2), y = rnorm(i^2))
}

myplots <- list()
for(i in 1:4) {
  stash(paste0("df", i), {
    df <- long_running_function(i)
  })
  myplots[[i]] <- ggplot(df, aes(x = x,y = y)) + geom_point()
}
patchwork::wrap_plots(myplots) + plot_layout(ncol=2)
```
(This doesn't work since I misinterpreted the documentation)

What I'd like is something like this:

```
for(i in 1:4) {
  df <- stash(paste0("df", i), {
    long_running_function(i)
  }, functional = TRUE)
  myplots[[i]] <- ggplot(df, aes(x = x,y = y)) + geom_point()
}
```

In my thinking, the `functional` parameter would prevent the `assign` call to the global environment and would instead return the value.

**Comment by jhrcook** [comment]
This is an interesting idea. I'll take a look at implementation this weekend. Otherwise, you can try to implement it yourself and create a PR.

**Comment by traversc** [comment]
Not sure if you saw this: https://github.com/jhrcook/mustashe/pull/17

**Comment by jhrcook** [comment]
Sorry for the delay, but I took a look through your changes and had a few minor comments. Most of the comments are about styling, but if you don't really care to fix those, that's fine. I'll eventually add a GH Action to handle styling in the future, anyway.

Thanks for the PR, I hope others find the new features useful, too!
