### ISSUE TITLE
Configuration option to set default for the `functional=` argument in `stash()`?

### ISSUE THREAD

**Issue by jhrcook** [jhrcook/mustashe#27]
Would it be useful to be able to set the default for the `functional` argument in `stash("var", { ... }, functional = .default_functional)`? The implementation would be easy enough and based off of that for the 'here' integration. It seems like some people generally want it to be `TRUE` while others want the original default behavior with default `FALSE`. 

Thoughts @torfason?

**Comment by torfason** [comment]
Yes, that would be great!

In fact, I'm already using it like that, by entering, `formals(stash)$functional<-TRUE` after loading the package. Absolute hack, but works for me for now. An actual config of default argument would of course be much better.

I wonder if `verbose` merits the same treatment? It is convenient to be able to turn of the (helpful) messages in some situations. With that, I think the logging functionality would be quite powerful enough for a focused package such as this, and I'm personally not sure that adding log4r as discussed in #3 would bring enough added benefits to justify the added dependency and complexity.

Finally, it might be worth considering if adding `use_*()` functions is the best way to go, or whether it would be better to bring it together in a single function, something like `mustache_options()` or `mustache_config()` that could allow setting all these options. Of course, it would be possible to just use base `options()`, but I always find that fiddly (and that does not allow custom processing and logging to be triggered). Just brainstorming here ...

**Comment by jhrcook** [comment]
I like the idea of a `mustashe_config()` function rolling the options for 'here', verbosity, and the default for `functional` default into a single function.

**Comment by jhrcook** [comment]
I've implemented `config_mustashe()` in PR #30 . Any thoughts? It doesn't change any behavior and the test suite passed without much fuss. I still need to update the vignettes, but I'll do that when I address #26 and #28.
