### ISSUE TITLE
Failing macOS CI test on development version of R

### ISSUE THREAD

**Issue by jhrcook** [jhrcook/mustashe#33]
Currently, the CI tests on macOS using the development version of R are failing. This is because the development version is not available for this operating system. It is available for Windows and Ubuntu, and the tests on these operating systems are successful. This issue will presumably be resolved when the development version of R reaches a stable beta.

**Comment by torfason** [comment]
This might have been caused by intermittent issues with R-devel, but it looks to me like there are also some issues with the old workflows, these have been causing issues with other packages I'm maintaining. I've submitted a PR, #34, with a suggested solution.

**Comment by jhrcook** [comment]
Closed by PR #34
