### ISSUE TITLE
Is renv needed?

### ISSUE THREAD

**Issue by torfason** [jhrcook/mustashe#35]
I am finding that there is a lot of extra time needed to update the environment for `renv` (due to downloading old packages, which for some reason took a long time), and I wonder if it is needed and worth the extra time and complexity. 

For a standalone data analysis project, `renv` makes a lot of sense, because you want to be able to run it without updating it to reflect any changes to the code due to updated dependency packages. For a _package_ however, if it does not work with the most recent versions of dependency packages, that would probably be considered a bug – and will cause it to be removed from CRAN eventually.

I therefore suggest removing `renv` from the project (a simple `renv::deactivate()` would update the .Rprofile file do do this).

**Comment by jhrcook** [comment]
Probably a good idea. Can let any developer decide to use it they want.
