### ISSUE TITLE
Cannot add functions as dependencies

### ISSUE THREAD

**Issue by jhrcook** [jhrcook/mustashe#8]
Due to how functions are compiled in R (beyond my understanding of R internals), functions cannot be included as dependencies. When they are called, their `digest()` codes change.

```
fxn <- function(x) {
    x ** 2
}

print(digest(fxn))
#> "096a999044001f53680df00e72c01df4"
print(digest(fxn))
#> "096a999044001f53680df00e72c01df4"
a <- fxn(2)
print(digest(fxn))
#> "468fa787fc71aa60fe373bd0bf6f0fc7"
a <- fxn(2)
print(digest(fxn))
#> "d9aef36674c50dcfb03a6fae3f20ce8c"
a <- fxn(4)
print(digest(fxn))
#> "d9aef36674c50dcfb03a6fae3f20ce8c"
```

This is because of the following difference:

```
fxn <- function(x) {
    x ** 2
}

fxn
#> function(x) {
#>        x ** 2
#>    }

a <- fxn(2)
a <- fxn(2)

fxn
#> function(x) {
#>         x ** 2
#>     }
#> <bytecode: 0x7f80b3f24ee8>
```

This may be able to be fixed by accounting for the bytecode with `class(var) == "function"` in `mustashe::make_hash()`.

**Comment by jhrcook** [comment]
https://github.com/eddelbuettel/digest/issues/92

**Comment by jhrcook** [comment]
Does ['memoise'](http://memoise.r-lib.org) keep track of the function? If they do, that might help with this issue.

**Comment by torfason** [comment]
Sorry to „reopen“ but I submitted a new PR with an improved fix for this, since upon thinking about it,`deparse1()` is a more robust way to pre-process functions than `body()``
